version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=runner-ms-db
      - POSTGRES_USER=runner_ms
      - POSTGRES_PASSWORD=secret

    ports:
      - "5432:5432"
